version: "3"

services:

  cb-server:
    image: couchbase/server:7.1.1
    healthcheck:
      test: ["CMD", "couchbase-cli", "server-info", "-u", "Administrator", "-p", "password", "-c", "http://localhost:8091"]
      start_period: 15s
    ports:
      - "8091-8094:8091-8094"
      - 11210:11210

  sync-gateway:
    image: local-sg
    build:
      context: sg
      ssh:
        - default
    ports:
      - 4984:4984
      - 4985:4985
    depends_on:
      cb-server:
        condition: service_healthy
